#ifndef IRE_ERRORS_H
#define IRE_ERRORS_H

#define IRE_OK   0x00
#define IRE_EXIT 0x01

#define IRE_ERROR_NOT_IMPLEMENTED 0x02
#define IRE_ERROR_NULL_POINTER    0x03
#define IRE_ERROR_OUT_OF_MEMORY   0x04

#endif
