#ifndef IRE_OPCODES_H
#define IRE_OPCODES_H

#define IRE_OPCODE_NOP  0x00
#define IRE_OPCODE_CPY  0x01
#define IRE_OPCODE_STO  0x02
#define IRE_OPCODE_LOD  0x03
#define IRE_OPCODE_PSH  0x04
#define IRE_OPCODE_POP  0x05
#define IRE_OPCODE_CAL  0x06
#define IRE_OPCODE_JMP  0x07
#define IRE_OPCODE_IRT  0x08
#define IRE_OPCODE_RET  0x09
#define IRE_OPCODE_IRET 0x0a
#define IRE_OPCODE_CMP  0x0b
#define IRE_OPCODE_ADD  0x0c
#define IRE_OPCODE_SUB  0x0d
#define IRE_OPCODE_MUL  0x0e
#define IRE_OPCODE_DIV  0x0f
#define IRE_OPCODE_MOD  0x10
#define IRE_OPCODE_NEG  0x11
#define IRE_OPCODE_AND  0x12
#define IRE_OPCODE_OR   0x13
#define IRE_OPCODE_XOR  0x14
#define IRE_OPCODE_NOT  0x15
#define IRE_OPCODE_SHL  0x16
#define IRE_OPCODE_SHR  0x17
#define IRE_OPCODE_ROL  0x18
#define IRE_OPCODE_ROR  0x19
#define IRE_OPCODE_IN   0x1a
#define IRE_OPCODE_OUT  0x1b
#define IRE_OPCODE_HLT  0x1c
#define IRE_OPCODE_HLTI 0x1d

#define IRE_OPCODE_CMPI 0x40
#define IRE_OPCODE_ADDI 0x41
#define IRE_OPCODE_SUBI 0x42
#define IRE_OPCODE_MULI 0x43
#define IRE_OPCODE_DIVI 0x44
#define IRE_OPCODE_MODI 0x45
#define IRE_OPCODE_ANDI 0x46
#define IRE_OPCODE_ORI  0x47
#define IRE_OPCODE_XORI 0x48
#define IRE_OPCODE_SHLI 0x49
#define IRE_OPCODE_SHRI 0x4a
#define IRE_OPCODE_ROLI 0x4b
#define IRE_OPCODE_RORI 0x4c
#define IRE_OPCODE_INI  0x4d
#define IRE_OPCODE_OUTI 0x4e

#define IRE_OPCODE_LODI 0x80
#define IRE_OPCODE_ESC  0x81
#define IRE_OPCODE_CALI 0x82
#define IRE_OPCODE_IRTI 0x83
#define IRE_OPCODE_JMPI 0x84

#endif
